#ifndef __FIRMWARE_VERSION_H
#define __FIRMWARE_VERSION_H

/* Generated by Bootloader/build_ota_release.ps1 before each release build. */
#define APP_FIRMWARE_VERSION 0x00010057UL
#define APP_FIRMWARE_VERSION_MAJOR 1U
#define APP_FIRMWARE_VERSION_MINOR 0U
#define APP_FIRMWARE_VERSION_PATCH 87U

#endif /* __FIRMWARE_VERSION_H */