#ifndef __STRESS_TABLE_H
#define __STRESS_TABLE_H

#include <stdint.h>

#define STRESS_TABLE_POINT_COUNT 45U
#define STRESS_SEGMENT_COUNT 9U
#define STRESS_LAST_SECTION_START_INDEX 40U
#define TEMPERATURE_TABLE_POINT_COUNT 54U
#define TEMPERATURE_SEGMENT_COUNT 9U
#define TEMPERATURE_FEEDBACK_SELECTOR_CH0 0U
#define TEMPERATURE_FEEDBACK_SELECTOR_CH1 1U
#define TEMPERATURE_ADC_SETTLE_US 12000U
#define TEMPERATURE_PRECONDITION_HOLD_US 5000U
#define STRESS_PATH_PRECONDITION_POINT_INDEX 2U
#define STRESS_PATH_PRECONDITION_HOLD_US 5000U

extern const uint16_t Stress_Wave_DAC[STRESS_TABLE_POINT_COUNT][5];
extern const uint16_t Stress_Wave_DATA[STRESS_TABLE_POINT_COUNT][2];
extern const uint16_t Stress_Path_Precondition_DAC[5];
extern const uint16_t Temperature_Precondition_DAC[TEMPERATURE_TABLE_POINT_COUNT][5];

#endif
