param(
    [string]$Version = "1.0.0"
)

$ErrorActionPreference = "Stop"
$Repository = Resolve-Path (Join-Path $PSScriptRoot "..\..")
$KeilBin = "D:\Keil_v5\ARM\ARMCLANG\Bin"
$Uv4 = "D:\Keil_v5\UV4\UV4.exe"
$Build = Join-Path $PSScriptRoot "build"
$Release = Join-Path $Repository "outputs\ota"
New-Item -ItemType Directory -Force $Build, $Release | Out-Null

$VersionParts = $Version.Split('.')
if ($VersionParts.Count -ne 3) {
    throw "Version must use major.minor.patch format"
}
$Major = 0
$Minor = 0
$Patch = 0
if (-not [int]::TryParse($VersionParts[0], [ref]$Major) -or
    -not [int]::TryParse($VersionParts[1], [ref]$Minor) -or
    -not [int]::TryParse($VersionParts[2], [ref]$Patch) -or
    $Major -lt 0 -or $Major -gt 255 -or
    $Minor -lt 0 -or $Minor -gt 255 -or
    $Patch -lt 0 -or $Patch -gt 255) {
    throw "Version components must be integers from 0 to 255"
}
$EncodedVersion = ($Major -shl 16) -bor ($Minor -shl 8) -bor $Patch
$VersionHeader = Join-Path $Repository "JDSU\Core\Inc\firmware_version.h"
$VersionHeaderText = @"
#ifndef __FIRMWARE_VERSION_H
#define __FIRMWARE_VERSION_H

/* Generated by Bootloader/build_ota_release.ps1 before each release build. */
#define APP_FIRMWARE_VERSION 0x$($EncodedVersion.ToString('X8'))UL
#define APP_FIRMWARE_VERSION_MAJOR $($Major)U
#define APP_FIRMWARE_VERSION_MINOR $($Minor)U
#define APP_FIRMWARE_VERSION_PATCH $($Patch)U

#endif /* __FIRMWARE_VERSION_H */
"@
[System.IO.File]::WriteAllText(
    $VersionHeader,
    $VersionHeaderText,
    [System.Text.UTF8Encoding]::new($false)
)

Push-Location (Join-Path $Repository "JDSU\MDK-ARM")
try {
    $BuildStartedUtc = [DateTime]::UtcNow
    $BuildLogName = "ota_app_build_$([Guid]::NewGuid().ToString('N')).log"
    & $Uv4 -b "JDSU.uvprojx" -j0 -o $BuildLogName
    $Deadline = (Get-Date).AddSeconds(45)
    do {
        Start-Sleep -Milliseconds 300
        $Log = if (Test-Path -LiteralPath $BuildLogName) {
            Get-Content -LiteralPath $BuildLogName -Raw
        } else { "" }
    } while ($Log -notmatch "Build Time Elapsed" -and (Get-Date) -lt $Deadline)
    if ($Log -notmatch "Build Time Elapsed") {
        throw "Keil application build timed out before this build completed"
    }
    if ($Log -notmatch "0 Error\(s\)") { throw "Keil 应用构建失败`n$Log" }
    $AxfDeadline = (Get-Date).AddSeconds(10)
    $ApplicationAxf = $null
    do {
        Start-Sleep -Milliseconds 100
        if (Test-Path -LiteralPath "JDSU\JDSU.axf") {
            $ApplicationAxf = Get-Item -LiteralPath "JDSU\JDSU.axf"
        }
    } while (
        ($null -eq $ApplicationAxf -or
         $ApplicationAxf.LastWriteTimeUtc -lt $BuildStartedUtc.AddSeconds(-1)) -and
        (Get-Date) -lt $AxfDeadline
    )
    if ($null -eq $ApplicationAxf -or
        $ApplicationAxf.LastWriteTimeUtc -lt $BuildStartedUtc.AddSeconds(-1)) {
        throw "Keil did not refresh the application AXF for this release"
    }
} finally {
    Pop-Location
}

& "$KeilBin\armasm.exe" --cpu Cortex-M3 --apcs=interwork --pd "__MICROLIB SETA 1" `
    -o "$Build\startup.o" "$Repository\JDSU\MDK-ARM\startup_stm32f205xx.s"
if ($LASTEXITCODE) { throw "OTA bootloader startup assembly failed" }

& "$KeilBin\armclang.exe" --target=arm-arm-none-eabi -mcpu=cortex-m3 -mthumb -Oz -g `
    -ffunction-sections -fdata-sections -DSTM32F205xx `
    -I"$Repository\JDSU\Core\Inc" `
    -I"$Repository\JDSU\Drivers\CMSIS\Device\ST\STM32F2xx\Include" `
    -I"$Repository\JDSU\Drivers\CMSIS\Include" `
    -c "$PSScriptRoot\ota_bootloader.c" -o "$Build\ota_bootloader.o"
if ($LASTEXITCODE) { throw "OTA bootloader compilation failed" }

& "$KeilBin\armlink.exe" --cpu Cortex-M3 "$Build\startup.o" "$Build\ota_bootloader.o" `
    --strict --scatter "$PSScriptRoot\OTA_Bootloader.sct" --map --symbols --info sizes `
    --list "$Build\OTA_Bootloader.map" -o "$Build\OTA_Bootloader.axf"
if ($LASTEXITCODE) { throw "OTA bootloader link failed" }

$BootloaderHex = Join-Path $Build "OTA_Bootloader.hex"
$BootloaderBin = Join-Path $Build "OTA_Bootloader.bin"
$ApplicationBin = Join-Path $Build "JDSU_OTA_App.bin"
# fromelf can leave a pre-existing output file untouched while still returning
# success.  Never allow a previous release image to be wrapped in a new package.
Remove-Item -LiteralPath $BootloaderHex, $BootloaderBin, $ApplicationBin `
    -Force -ErrorAction SilentlyContinue

& "$KeilBin\fromelf.exe" --i32combined --output $BootloaderHex "$Build\OTA_Bootloader.axf"
if ($LASTEXITCODE -or -not (Test-Path -LiteralPath $BootloaderHex)) {
    throw "OTA bootloader HEX extraction failed"
}
& "$KeilBin\fromelf.exe" --bin --output $BootloaderBin "$Build\OTA_Bootloader.axf"
if ($LASTEXITCODE -or -not (Test-Path -LiteralPath $BootloaderBin)) {
    throw "OTA bootloader BIN extraction failed"
}
& "$KeilBin\fromelf.exe" --bin --output $ApplicationBin `
    "$Repository\JDSU\MDK-ARM\JDSU\JDSU.axf"
if ($LASTEXITCODE -or -not (Test-Path -LiteralPath $ApplicationBin)) {
    throw "OTA application BIN extraction failed"
}

$Python = Join-Path $Repository "Python\.venv\Scripts\python.exe"
if (-not (Test-Path $Python)) { $Python = "python" }
& $Python "$Repository\Python\package_firmware.py" $ApplicationBin `
    --version $Version --output "$Release\JDSU_F205RE_v$Version.fbgfw"
if ($LASTEXITCODE) { throw "OTA package generation failed" }
& $Python "$Repository\Python\make_initial_ota_installer.py" `
    $BootloaderHex "$Repository\JDSU\MDK-ARM\JDSU\JDSU.hex" `
    "$Release\JDSU_OTA_FirstInstall_v$Version.hex"
if ($LASTEXITCODE) { throw "Initial installer merge failed" }

# UV4 reports completion before its log handle is necessarily quiescent.  Copy
# the final bytes only after package generation, then verify the archived log
# still contains the same successful terminal marker used by the build gate.
$SourceBuildLog = Join-Path $Repository "JDSU\MDK-ARM\$BuildLogName"
$FinalBuildLog = Join-Path $Repository "JDSU\MDK-ARM\ota_app_build.log"
$FinalBuildText = [System.IO.File]::ReadAllText($SourceBuildLog)
if ($FinalBuildText -notmatch "Build Time Elapsed" -or
    $FinalBuildText -notmatch "0 Error\(s\)") {
    throw "Keil application build log was incomplete after package generation"
}
[System.IO.File]::WriteAllBytes(
    $FinalBuildLog,
    [System.IO.File]::ReadAllBytes($SourceBuildLog)
)

Write-Host "OTA release generated in $Release"
